version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bayar-service-app
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "java", "-jar", "app.jar"]
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_CONTAINER_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}

  postgres:
    image: "postgres:15.0-alpine"
    container_name: bayar-service-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
